### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by DiamondGlassDrill** [Muhammad-Ibraheem-Siddiqui/PerSense#1]
Thanks for this amazing work!!!
I wonder, if you could tell me what the latency is per image detection in e.g. 3090ti? Or similar. 
Can the model be used for real time purpose?

Thanks in advance

**Comment by Muhammad-Ibraheem-Siddiqui** [comment]
Thanks for your interest in our work. We have tested it on RTX 4090 and it takes ~2.5 sec to predict instance segmentation mask for an extremely dense image. Currently, our focus was not real time performance but on introducing this novel paradigm where density maps can be efficiently utilized for instance segmentation tasks in dense images. More efficient implementations with lightweight models are possible but there will be a trade-off between segmentation accuracy and computational speed which is subjective to the real-world use case. Hope this answers your question.

**Comment by DiamondGlassDrill** [comment]
Thanks @Muhammad-Ibraheem-Siddiqui again awesome work! And thanks for the quick reply. Helps a lot.
So for data auto labeling and data label enrichment a perfect tool!!!
Which in fact makes the real world labeled data even better and faster.
Super work!

**Comment by Muhammad-Ibraheem-Siddiqui** [comment]
Thanks.
